---
- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: "System | Run Tasks: {{ ansible_os_family }}"
      ansible.builtin.include_tasks: "tasks/debian.yml"
      when: ansible_facts['os_family'] == "Debian"    
    - name: "System | Run Tasks: {{ ansible_os_family }}"
      ansible.builtin.include_tasks: "tasks/redhat.yml"
      when: ansible_facts['os_family'] == "RedHat"
    - name: "System | Run Tasks: {{ ansible_os_family }}"
      ansible.builtin.include_tasks: "tasks/archlinux.yml"
      when: ansible_facts['os_family'] == "Archlinux"
      
    - name: Get current timezone
      ansible.builtin.command: timedatectl show --property=Timezone --value
      register: current_timezone
      changed_when: false
    
    - name: Set timezone to Africa/Cairo
      community.general.timezone:
        name: Africa/Cairo
      become: yes
      become_method: sudo
      when: current_timezone.stdout != 'Africa/Cairo'
