---
- hosts: home
  gather_facts: yes
  become: true
  tasks:
    - name: Set OS-specific task file path
      set_fact:
        os_task_file: "tasks/{{ ansible_facts['os_family'] | lower }}.yml"

    - name: Check if OS-specific task file exists
      stat:
        path: "{{ os_task_file }}"
      register: os_file_check
      delegate_to: localhost

    - name: Include OS-specific tasks
      ansible.builtin.include_tasks: "{{ os_task_file }}"
      when: os_file_check.stat.exists

    - name: Display warning if OS-specific file not found
      ansible.builtin.debug:
        msg: "Warning: No task file found for {{ ansible_facts['os_family'] }} ({{ os_task_file }})"
      when: not os_file_check.stat.exists

    - name: Move log file with timestamp and keep only last 10 logs
      ansible.builtin.shell: |
        mv ./ansible.log ./logs/ansible_$(date +%Y%m%d_%H%M%S).log
        cd ./logs && ls -t ansible_*.log | tail -n +11 | xargs -r rm --
      delegate_to: localhost
      run_once: true
