---
- hosts: pve
  gather_facts: no
  become: true
  tasks:
    - name: BAT | DEBIAN | Install deb from github
      become: true
      ansible.builtin.apt:
        name: bat
        state: latest
    - name: Set OS-specific task file path
      set_fact:
        os_task_file: "tasks/{{ ansible_facts['os_family'] | lower }}.yml"

    - name: Check if OS-specific task file exists
      stat:
        path: "{{ os_task_file }}"
      register: os_file_check
      delegate_to: localhost

    - name: Include OS-specific tasks
      ansible.builtin.include_tasks: "{{ os_task_file }}"
      when: os_file_check.stat.exists

    - name: Display warning if OS-specific file not found
      ansible.builtin.debug:
        msg: "Warning: No task file found for {{ ansible_facts['os_family'] }} ({{ os_task_file }})"
      when: not os_file_check.stat.exists
