---
- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: "System | Checking for Distribution Config: {{ ansible_os_family }}"
      ansible.builtin.stat:
        path: "tasks/{{ ansible_os_family }}.yml"
      register: ansible_os_config
    
    - name: "System | Run Tasks: {{ ansible_os_family }}"
      ansible.builtin.include_tasks: "tasks/{{ ansible_os_family }}.yml"
      when: ansible_os_config.stat.exists
      
    - name: Get current timezone
      ansible.builtin.command: timedatectl show --property=Timezone --value
      register: current_timezone
      changed_when: false
    
    - name: Set timezone to Africa/Cairo
      community.general.timezone:
        name: Africa/Cairo
      become: yes
      become_method: sudo
      when: current_timezone.stdout != 'Africa/Cairo'
